using System.Collections.Generic;

public class Scenes {
    static Dictionary<string, Scene> _lookup = new Dictionary<string, Scene> {
        { "waking", new Scene(
                SET.TIME(0800),
                SET.BG(""),
                SET.MSG("( ... )"),
                A.WAIT(),
                SET.MSG("( you can hear the most horrible sound )"),
                A.WAIT(),
                SET.MSG("*BZZZT* *BZZZT* *BZZZT*"),
                SET.CHOICES(
                    new Choice("Snooze...", INC.TIME(0010)),
                    new Choice("Open your eyes, turn it off", A.GOTO("awake"))
                ),
                SET.MSG("( ... )"),
                A.WAIT(),
                SET.MSG("*BZZZT* *BZZZT* *BZZZT*"),
                SET.CHOICES(
                    null,
                    new Choice("Open your eyes, turn it off", A.GOTO("awake"))
                ),
            A.LABEL("awake"),
                SET.BG("waking-up"),
                SET.MSG("Ah, another fine school day. ( you urgently need the restroom )"),
                A.WAIT(),
                SET.SCENE("bathroom")
            ) },

        { "bathroom", new Scene(
                SET.BG("bathroom"),
                INC.TIME(0001),
                SET.MSG("( after a brief repose you are feeling more settled )"),
                SET.CHOICES(
                    new Choice("Leave the bathroom", SET.SCENE("house")),
                    new Choice("Look in the mirror", SET.BG("mirror"))),
                SET.MSG("As good as can be expected, I'd say."),
                SET.FLAG("looked-in-mirror"),
                A.WAIT(),
                INC.TIME(0005),
                SET.MSG("Better start getting ready to go - the bus leaves at 8:35."),
                A.WAIT(),
                SET.SCENE("house")
            ) },

        { "house", new Scene(
                SET.BG("house"),
                SET.MSG("Hello, world."),
                SET.CHOICES(
                    new Choice("Watch TV for a bit"),
                    new Choice("Head to the bus stop early", A.GOTO("bus-early"))
                ),
                INC.TIME(0005),
                SET.BG("tv-1"),
                SET.MSG("( sports highlights from the night before )"),
                SET.CHOICES(
                    new Choice("Watch", A.MULTI(INC.STAT("POP", 5), A.GOTO("tv-watched"))),
                    new Choice("Next channel", A.SOUND("tvStatic"))
                ),
                SET.BG("tv-2"),
                SET.MSG("( an educational program )"),
                SET.CHOICES(
                    new Choice("Watch", A.MULTI(INC.STAT("GPA", 5), A.GOTO("tv-watched"))),
                    new Choice("Next channel", A.SOUND("tvStatic"))
                ),
                SET.BG("tv-3"),
                SET.MSG("( a trivia show )"),
                SET.CHOICES(
                    new Choice("Watch", A.MULTI(INC.STAT("CLV", 5), A.GOTO("tv-watched"))),
                    new Choice("Next channel", A.SOUND("tvStatic"))
                ),
                SET.BG("tv-4"),
                SET.MSG("( a documentary about refugees )"),
                SET.CHOICES(
                    new Choice("Watch", A.MULTI(INC.STAT("EMP", 5), SET.FLAG("documentary-watched"), A.GOTO("tv-watched"))),
                    new Choice("Turn it off", A.SOUND("hit"))
                ),
                SET.BG("house"),
                SET.MSG("Not much to watch."),
                A.WAIT(),
                A.GOTO("leave"),
            A.LABEL("tv-watched"),
                INC.TIME(0015),
            A.LABEL("leave"),
                SET.BG("house"),
                COND.IF(COND.BEFORE(0829),
                    A.GOTO("bus-on-time")),
                SET.MSG("I feel like I was forgetting something..."),
                A.WAIT(1.5f),
                SET.MSG("THE BUS! IT'S GOING TO LEAVE WITHOUT ME (again)", TextEffect.VIBRATE),
                A.WAIT(),
                SET.SCENE("run-to-bus"),
            A.LABEL("bus-on-time"),
                SET.MSG("Time to get going anyway."),
                A.WAIT(),
                SET.SCENE("bus-stop"),
            A.LABEL("bus-early"),
                SET.MSG("I'd rather take my time, anyway."),
                A.WAIT(),
                SET.SCENE("bus-stop")
            ) },

        { "bus-stop", new Scene(
                SET.BG("bus-stop"),
                COND.IF(COND.AFTER(0832), A.GOTO("get-on")),
                SET.MSG("There's someone new here I don't recognize..."),
                SET.CHOICES(
                    new Choice("Talk to him", A.GOTO("talk-to-james")),
                    new Choice("Wait on your own", A.NOOP())
                ),
                SET.MSG("( ... )"),
                A.WAIT(),
                A.GOTO("get-on"),
            A.LABEL("talk-to-james"),
                SET.BG("james-bus"),
                SET.MSG("Hey there! ( he looks nervous )"),
                A.WAIT(),
                SET.MSG("'Hi... James. My name is James, I'm-"),
                SET.CHOICES(new Choice("..."), new Choice("New?", INC.STAT("CLV", 2, false))),
                SET.MSG("'I'm a new sophomore, I just transferred.'"),
                SET.CHOICES(
                    new Choice("'Just stay out of the way. MY way I mean'", A.NOOP()),
                    new Choice("'Great to meet you, come find me if you need any help'", A.GOTO("nice"))
                ),
                INC.STAT("POP", 10),
                INC.STAT("EMP", -10),
                SET.FLAG("mean-to-james"),
                A.GOTO("get-on"),
            A.LABEL("nice"),
                SET.MSG("( he smiles a bit, blushing slightly )"),
                A.WAIT(),
                SET.FLAG("nice-to-james"),
                INC.STAT("EMP", 10),
            A.LABEL("get-on"),
                SET.BG("bus-outside"),
                SET.MSG("The bus is here, time to get on."),
                A.WAIT(),
                SET.SCENE("bus")
            ) },

        { "bus", new Scene(
                SET.BG("bus-inside"),
                COND.IF(COND.BEFORE(0840),
                    SET.TIME(0840),
                    A.GOTO("late")
                ),
                SET.MSG("( your friend Nina has an open seat -- she's looking out the window )"),
                SET.CHOICES(
                    new Choice("Sit with Nina"),
                    new Choice("Sit further back", A.GOTO("late"))
                ),
                SET.BG("nina-bus"),
                SET.MSG("( you sit down next to Nina, she turns to you )"),
                A.WAIT(),
                SET.MSG("( she looks cheerful, but not quite so much as usual )"),
                COND.IF(COND.FLAGGED("documentary-watched"),
                    SET.CHOICES(
                        new Choice("'Did you catch any of that documentary this morning?'"),
                        new Choice("'How are you doing today?'", A.GOTO("nina-talk"))
                    ),
                    SET.CHOICES(
                        new Choice("'We still on to study later?'", A.GOTO("nina-study")),
                        new Choice("'How are you doing today?'", A.GOTO("nina-talk"))
                    )
                ),
                SET.MSG("'I did! The footage was so heartbreaking...'"),
                A.WAIT(),
                INC.STAT("EMP", 5),
                SET.MSG("( you and Nina chat briefly )"),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("nina-study"),
                SET.MSG("'Of course! We are going to ace the quiz on Friday.'"),
                A.WAIT(),
                SET.MSG("( she smiles confidently at you )"),
                INC.STAT("GPA", 15),
                A.GOTO("end"),
            A.LABEL("nina-talk"),
                SET.MSG("( she smiles and opens her mouth, then pauses )"),
                A.WAIT(),
                INC.STAT("EMP", 10),
                SET.MSG("'Actually I'm a bit conflicted...'"),
                SET.CHOICES(null, new Choice("'What's wrong?'")),
                SET.MSG("'I've just been worried. About Simon."),
                SET.CHOICES(
                    new Choice("'Is he okay?'", SET.MSG("'Yes. Well, no.'")),
                    new Choice("'What about Simon?'", SET.MSG("'Just...'"))
                ),
                A.WAIT(),
                SET.MSG("'He's been acting really depressed lately, to be honest.'"),
                SET.CHOICES(
                    new Choice("'He's been a bit moody, yeah.'", A.GOTO("nina-talk-end")),
                    new Choice("'I hope he's alright...'")
                ),
                SET.MSG("'You should talk with him, he likes talking to you'"),
                SET.CHOICES(null, new Choice("'Okay, I'll see what I can do'")),
                SET.MSG("'We're having lunch together if you want to meet us.'"),
                A.WAIT(),
                INC.STAT("EMP", 5),
                A.GOTO("end"),
            A.LABEL("nina-talk-end"),
                SET.MSG("'Yeah...' ( she looks out the window again )"),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("late"),
                SET.MSG("( there's a free seat near the back )"),
                A.WAIT(),
                SET.MSG("( you take a seat beside Charlotte )"),
                A.WAIT(),
                SET.BG("charlotte-bus"),
                INC.STAT("POP", -5),
                SET.MSG("( you don't know her well, she's a bit of a loner )"),
                SET.CHOICES(
                    new Choice("Say hello", A.GOTO("charlotte-talk")),
                    new Choice("Keep to yourself")
                ),
                SET.MSG("( you keep quiet and so does Charlotte )"),
                A.WAIT(),
                INC.STAT("RBL", 5),
                INC.STAT("EMP", 5),
            A.LABEL("end"),
                SET.MSG("( the bus arrives )"),
                A.WAIT(2f),
                SET.SCENE("school-start"),
            A.LABEL("charlotte-talk"),
                SET.MSG("( Charlotte gives you a look, judging your commitment to conversation )"),
                SET.CHOICES(
                    new Choice("'Charlotte, right? We had the same homeroom last year'"),
                    new Choice("Wait", A.GOTO("end"))
                ),
                SET.MSG("( her look softens, slightly )"),
                SET.CHOICES(
                    new Choice("'You looked a bit lonely...'", A.GOTO("charlotte-unhappy")),
                    new Choice("'Anyway, good to see you'")
                ),
                SET.MSG("'Same.' ( it occurs to you that this is the first time you've spoken )"),
                A.WAIT(),
                INC.STAT("EMP", 10),
                INC.STAT("CLV", 5),
                SET.FLAG("yes-charlotte"),
                A.GOTO("end"),
            A.LABEL("charlotte-unhappy"),
                SET.MSG("( Charlotte rolls her eyes and turns away )"),
                INC.STAT("EMP", -5),
                SET.FLAG("no-charlotte"),
                A.GOTO("end")
            ) },

        { "run-to-bus", new Scene(
                SET.BG("bus-late"),
                SET.MSG("( alternate left and right rapidly to run )"),
                A.WAIT(),
                SET.PROP("bus-distance", 100),
            A.LABEL("start-run"),
                SET.CHOICES(null,
                    new Choice("RUN!", A.MULTI(INC.PROP("bus-distance", -1), A.SOUND("step")), false)),
                SET.CHOICES(new Choice("RUN!", A.MULTI(INC.PROP("bus-distance", -1), A.SOUND("step")), false),
                    null),
                COND.IF(COND.LT("bus-distance", 1),
                    A.GOTO("done")),
                COND.IF(COND.LT("bus-distance", 22),
                    A.GOTO("<22")),
                COND.IF(COND.LT("bus-distance", 45),
                    A.GOTO("<45")),
                COND.IF(COND.LT("bus-distance", 70),
                    A.GOTO("<70")),
                A.GOTO("start-run"),
            A.LABEL("<70"),
                SET.MSG("PLEASE DON'T LEAVE"),
                A.GOTO("start-run"),
            A.LABEL("<45"),
                SET.MSG("I CAN'T BE LATE AGAIN"),
                A.GOTO("start-run"),
            A.LABEL("<22"),
                SET.MSG("SO CLOSE!"),
                A.GOTO("start-run"),
            A.LABEL("done"),
                SET.TIME(0841),
                SET.MSG("Phew..."),
                A.WAIT(4),
                SET.SCENE("bus")) },

        { "school-start", new Scene(
                SET.TIME(0855),
                SET.BG("lockers"),
                SET.MSG("( by the lockers is Ellie, a very popular girl in your class )"),
                SET.CHOICES(new Choice("Go talk to Ellie"), new Choice("Keep moving", A.GOTO("next"))),
                COND.IF(COND.GT("POP", 20), // TODO TUNE THIS
                    A.GOTO("popular")),
                SET.MSG("( as you approach Ellie she glances at you without turning )"),
                SET.CHOICES(
                    new Choice("Say something"),
                    new Choice("Walk away", A.GOTO("walk-away"))
                ),
                SET.MSG("'Hi Ellie. How are you?"),
                A.WAIT(),
                SET.MSG("'Not great now that I've been interrupted. I should be going anyway'"),
                A.WAIT(),
                INC.TIME(4),
                INC.STAT("POP", -10),
                INC.STAT("EMP", 5),
                INC.STAT("CLV", -3),
                A.GOTO("next"),
            A.LABEL("walk-away"),
                INC.TIME(2),
                SET.MSG("( leaving, you can hear Ellie stifle a laugh, along with your name )"),
                A.WAIT(),
                A.GOTO("next"),
            A.LABEL("popular"),
                SET.MSG("( as you approach Ellie she turns to you and grins )"),
                A.WAIT(),
                SET.MSG("'Good to see you today!' Ellie says."),
                SET.CHOICES(
                    new Choice("'You too...'"),
                    new Choice("'You're... chipper.'")
                ),
                SET.MSG("'Listen, you should come find me at lunch! We need to catch up.'"),
                SET.FLAG("ellie-lunch"),
                A.WAIT(),
                SET.MSG("( as far as you know, you've never had anything to catch up on with Ellie )"),
                A.WAIT(),
                SET.MSG("'See you!' ( the bell rings )"),
                A.WAIT(),
                INC.TIME(5),
                A.GOTO("end"),
            A.LABEL("next"),
                COND.IF(COND.AND(COND.BEFORE(0858), COND.FLAGGED("yes-charlotte")), A.GOTO("charlotte")),
                SET.MSG("( you head over to your locker, and stash your extra books )"),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("charlotte"),
                SET.MSG("( you head over to your locker -- to your surprise, Charlotte is there )"),
                A.WAIT(),
                SET.MSG("'Listen, you seemed cool before... maybe we could talk at lunch?"),
                SET.CHOICES(
                    new Choice("'I'd like that'"),
                    new Choice("'I already have plans'", A.GOTO("deny"))
                ),
                SET.MSG("'Great. I'm usually outside around then.'"),
                SET.FLAG("charlotte-lunch"),
                A.WAIT(),
                A.GOTO("accept"),
            A.LABEL("deny"),
                SET.MSG("'Sure, I figured you would.'"),
                A.WAIT(),
                SET.MSG("( Charlotte slips away quickly )"),
                A.WAIT(),
            A.LABEL("accept"),
                SET.MSG("( the bell rings )"),
                A.WAIT(),
            A.LABEL("end"),
                SET.MSG("Better head to first period: American History"),
                A.WAIT(2),
                SET.SCENE("first-period")
            ) },

        {"first-period", new Scene(
                SET.TIME(0901),
                SET.BG("notes-blank"),
                SET.MSG("Time to take history notes"),
                SET.CHOICES(
                    new Choice("Write with left hand.", A.GOTO("good-notes")),
                    new Choice("Write with right hand.",
                        A.MULTI(
                            SET.MSG("Oh yeah... I'm still a lefty."),
                            SET.BG("notes-scribble"),
                            SET.FLAG("tried-left-hand"),
                            INC.TIME(0015)
                        )
                    )
                ),
                SET.CHOICES(new Choice("Write with Left hand."), null),
            A.LABEL("good-notes"),
                SET.BG("notes-neat"),
                INC.TIME(0045),
                INC.STAT("GPA", 10),
                COND.IF(COND.FLAGGED("tried-left-hand"),
                    SET.MSG("Much better"),
                    SET.MSG("So... much... history...")
                ),
                A.WAIT(),
                SET.MSG("( first period passes slowly )"),
                A.WAIT(3),
                SET.TIME(1015),
                SET.SCENE("lockers")) },

        { "lockers", new Scene(
                SET.BG("lockers"),
                SET.MSG("( Nina and Simon are by your locker )"),
                SET.CHOICES(
                    new Choice("Avoid them", A.GOTO("avoid")),
                    new Choice("Greet them")
                ),
                SET.MSG("'I think I've had about enough of the Revolutionary war'"),
                A.WAIT(),
                SET.MSG("( Nina chuckles in agreement, Simon shrugs )"),
                A.WAIT(),
                SET.CHOICES(
                    new Choice("Ask Simon what's wrong", A.GOTO("ask-simon")),
                    new Choice("Remind them about lunch")
                ),
                SET.MSG("'Looking forward to that lunch! Don't stand me up this time.'"),
                A.WAIT(),
                SET.MSG("( Simon grins sheepishly at that )"),
                A.WAIT(),
                INC.STAT("EMP", 10),
                A.GOTO("end"),
            A.LABEL("ask-simon"),
                SET.MSG("'Why so down, Simon?'"),
                A.WAIT(),
                SET.MSG("'Oh? I'm fine. Just a bit distracted...'"),
                A.WAIT(2),
                A.GOTO("end"),
            A.LABEL("avoid"),
                SET.MSG("( you turn around before they see you )"),
                A.WAIT(),
                INC.STAT("RBL", 10),
            A.LABEL("end"),
                SET.MSG("( the passing bell chimes )"),
                A.WAIT(),
                SET.MSG("Time for second period..."),
                A.WAIT(2),
                SET.SCENE("test")) },

        { "test", new Scene(
                SET.BG("class"),
                SET.TIME(1020),
                SET.MSG("( on each desk is a stack of paper )"),
                A.WAIT(),
                SET.MSG("( you take a seat and start to leaf through them )"),
                A.WAIT(),
                SET.MSG("( it's an 'Aptitude' test... )"),
                A.WAIT(),
            A.LABEL("before"),
                SET.CHOICES(
                    new Choice("Pick up your pen", A.GOTO("start")),
                    new Choice("Don't start it yet")
                ),
                SET.MSG("( you're not a fan of these )"),
                A.WAIT(),
                SET.MSG("( ... )"),
                A.WAIT(1.5f),
                INC.STAT("RBL", 5),
                INC.TIME(15),
                COND.IF(COND.BEFORE(1130),
                    A.GOTO("before"),
                    A.GOTO("end-blank")),
            A.LABEL("start"),
                SET.MSG("'Are you a ''People Person''?'"),
                SET.CHOICES(
                    new Choice("Yes", INC.STAT("EMP", 5)),
                    new Choice("No", INC.STAT("EMP", -1)), 5.0f
                ),
                INC.TIME(15),
                SET.MSG("'You witness a peer acting suspicious, do you:'"),
                SET.CHOICES(
                    new Choice("'A: Tell your manager'", INC.STAT("POP", 5)),
                    new Choice("'B: Investigate further'", INC.STAT("CLV", 5)), 4.5f
                ),
                INC.TIME(15),
                SET.MSG("'Are you more likely to be found:'"),
                SET.CHOICES(
                    new Choice("'A: Outside in the sun'", INC.STAT("POP", 5)),
                    new Choice("'B: Inside with a book'", INC.STAT("CLV", 5)), 4.0f
                ),
                SET.MSG("( weird choices... )"),
                A.WAIT(),
                INC.TIME(15),
                SET.MSG("'Which describes you best:'"),
                SET.CHOICES(
                    new Choice("'A: I am the center of attention'"),
                    new Choice("'B: No one likes me'"), 3.0f
                ),
                SET.MSG("( seriously...? )"),
                A.WAIT(),
                INC.TIME(15),
                SET.MSG("'Why are you taking this test?'"),
                SET.CHOICES(
                    new Choice("'It is required of me'"),
                    new Choice("'I enjoy tests'"), 2.5f
                ),
                SET.MSG("( ... )"),
                A.WAIT(),
                INC.TIME(15),
                A.GOTO("end"),
            A.LABEL("end-blank"),
                SET.MSG("( as the bell rings, the test sits before you untouched )"),
                A.WAIT(),
                INC.STAT("RBL", 5),
                INC.STAT("GPA", -10),
                A.WAIT(2),
                SET.SCENE("lunch"),
            A.LABEL("end"),
                SET.MSG("( as the bell rings, you've completed most of the test )"),
                A.WAIT(2),
                SET.SCENE("lunch")) },

        { "lunch", new Scene(
                SET.BG("lunch"),
                SET.MSG("Lunchtime. The cafeteria is busy, as usual."),
            A.LABEL("start"),
                SET.MSG("( you scan the tables in the room )"),
                SET.CHOICES(
                    new Choice("Sit with Nina and Simon", A.GOTO("nina-simon")),
                    new Choice("Look around")),

                COND.IF(COND.FLAGGED("ellie-lunch"),
                    SET.CHOICES(
                        new Choice("Sit with Ellie", A.GOTO("ellie")),
                        new Choice("Keep looking"))
                ),
                COND.IF(COND.FLAGGED("charlotte-lunch"),
                    SET.CHOICES(
                        new Choice("Go look outside for Charlotte", A.GOTO("charlotte")),
                        new Choice("Keep looking"))
                ),
                COND.IF(COND.FLAGGED("mean-to-james"),
                    A.MULTI(
                        SET.MSG("( everywhere else is full )"),
                        A.WAIT()
                    ),
                    A.MULTI(
                        SET.MSG("( you see the new kid, James, sitting alone )"),
                        SET.CHOICES(
                            new Choice("Sit with James", A.GOTO("james")),
                            new Choice("Keep looking"))
                    )
                ),
                A.GOTO("start"),
            A.LABEL("nina-simon"),
                SET.MSG("'Oh good, you found us. Crazy today!' Nina says."),
                SET.CHOICES(
                    new Choice("'Yeah it is.'"),
                    new Choice("Talk to Simon", A.GOTO("talk-simon"))
                ),
                SET.MSG("'I only got this table because I was here early to rewrite my notes.'"),
                SET.CHOICES(
                    new Choice("Talk about school"),
                    new Choice("Talk to Simon", A.GOTO("talk-simon"))
                ),
                SET.MSG("( you bring up your counseling appointment next period )"),
                A.WAIT(),
                COND.IF(COND.GTE("GPA", 340), 
                        SET.MSG("'Don't worry, you've got admissions in the bag' Nina chimes in."),
                        SET.MSG("'You have been... a little less focused lately,' Nina mentions.")
                ),
                SET.MSG("'Well let's just say I'm apprehensive. I need a good recommendation.'"),
                A.WAIT(),
                SET.MSG("( your friends give encouraging words )"),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("talk-simon"),
                SET.MSG("( Simon looks uncomfortable as you turn to him )"),
                SET.CHOICES(
                    new Choice("Ask about school", SET.MSG("'It's fine, I'm running out of classes to take.'")),
                    new Choice("Ask about home", SET.MSG("'Not much to say.'"))
                ),
                SET.CHOICES(
                    new Choice("'Are you getting enough sleep?'"),
                    new Choice("'How's your family?'")
                ),
                SET.MSG("'It's fine, really, it's ALL FINE!'"),
                SET.FLAG("simon-mad"),
                A.WAIT(3.0f),
                SET.MSG("'Sorry, I just... I don't need a reason for how I feel.'"),
                A.WAIT(),
                SET.MSG("( Simon stands up and leaves )"),
                A.WAIT(1),
                SET.MSG("'That was odd. Not like him.' Nina says."),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("ellie"),
                SET.MSG("'So lovely to see you again!' Ellie coos."),
                A.WAIT(),
                INC.STAT("POP", 15),
                SET.MSG("( you 'chat' with Ellie and her many friends over lunch )"),
                A.WAIT(2),
                A.GOTO("end"),
            A.LABEL("charlotte"),
                SET.MSG("( outside, you find Charlotte as promised )"),
                A.WAIT(),
                SET.MSG("( you sit and eat quietly for while )"),
                A.WAIT(2),
                SET.MSG("'So aren't you going to ask me some questions?'"),
                SET.CHOICES(
                    new Choice("'What?'"),
                    new Choice("'No'", A.GOTO("no-questions"))
                ),
                SET.MSG("'You know, the getting-to-know-you bit'"),
            A.LABEL("what-questions"),
                SET.CHOICES(
                    new Choice("'Well... what's your \"story\" then?'"),
                    new Choice("'I thought you liked that I wasn't chatting your ear off.'", A.GOTO("like-quiet"))
                ),
            A.LABEL("story"),
                SET.MSG("'I mean, there's not really that much to know.'"),
                A.WAIT(),
                SET.MSG("'I take care of my little brother, and I go to school because I promised I would.'"),
                SET.CHOICES(
                    new Choice("'You take care of your brother?'"),
                    new Choice("'You promised?'", A.GOTO("promise"))
                ),
                SET.MSG("'My mom left us one day, just like that. So, yeah I do.'"),
                SET.CHOICES(
                    new Choice("'She left you?'", A.GOTO("left")),
                    new Choice("'I'm sorry'", A.GOTO("sorry")),
                    2.5f
                ),
                SET.MSG("'Look it's really not that big of a deal.'"),
                A.WAIT(),
                A.GOTO("move-on"),
            A.LABEL("sorry"),
                SET.MSG("'Well... thanks. I'm not that upset about it.'"),
                A.WAIT(),
                A.GOTO("move-on"),
            A.LABEL("left"),
                SET.MSG("'We were in the laundromat, and then she just... wasn't.'"),
                SET.FLAG("laundromat"),
                A.WAIT(),
                A.GOTO("move-on"),
            A.LABEL("promise"),
                SET.MSG("'Yeah, something like that..."),
                A.WAIT(),
            A.LABEL("move-on"),
                SET.MSG("'Let's move on. What is YOUR story, eh?'"),
                A.WAIT(),
                SET.MSG("( Charlotte is in a jovial mood as you keep talking )"),
                A.WAIT(),
                SET.MSG("( you continue sharing for a while longer )"),
                A.WAIT(2),
                SET.MSG("'Class is about to start. How'd you like to do something else instead?'"),
                SET.CHOICES(
                    new Choice("'I don't know'"),
                    new Choice("Agree", A.GOTO("leave"))
                ),
                SET.MSG("'Trust me, it will be much better than third period. No one will notice.'"),
                SET.CHOICES(
                    new Choice("'I can't.'"),
                    new Choice("Agree", A.GOTO("leave"))
                ),
                SET.MSG("'Oh well. Some other time.'"),
                A.WAIT(),
                SET.MSG("( Charlotte looks wistful )"),
                A.WAIT(),
                A.GOTO("end"),
            A.LABEL("leave"),
                SET.MSG("'Awesome, let's do it.'"),
                A.WAIT(),
                INC.STAT("RBL", 20),
                INC.STAT("GPA", -10),
                SET.MSG("( feeling apprehensive, you leave with Charlotte )"),
                A.WAIT(2),
                SET.SCENE("charlotte"),
            A.LABEL("like-quiet"),
                SET.MSG("'Well, yeah. But I still want to know who you are.'"),
                A.WAIT(),
                SET.MSG("'And you might as well know who I am, better now than later.'"),
                A.WAIT(),
                A.GOTO("story"),
            A.LABEL("no-questions"),
                SET.MSG("'Hmm, right. You're either interested or you're not.'"),
                A.GOTO("what-questions"),
            A.LABEL("james"),
                SET.FLAG("nice-to-james"),
                SET.MSG("( James looks up and sees you, surprised but pleased )"),
                SET.CHOICES(
                    new Choice("'Is this seat taken?'"),
                    new Choice("'Want to join my friends' table?'", A.GOTO("join"))
                ),
                SET.MSG("'No, you're welcome to have it. I was just leaving anyway'"),
                A.WAIT(),
                SET.MSG("'So soon?'"),
                A.WAIT(),
                SET.MSG("'I'm not very hungry. There's a test next period I didn't know about...'"),
                A.WAIT(),
                SET.CHOICES(
                    new Choice("Offer to help study", INC.STAT("GPA", 15)),
                    new Choice("'How about some conversation to distract you'", INC.STAT("EMP", 5))
                ),
                SET.MSG("( you spend the lunch period with James, and he is noticeably happier )"),
                A.GOTO("end"),
            A.LABEL("join"),
                SET.MSG("( James accompanies you to Nina and Simon's table )"),
                A.WAIT(),
                INC.STAT("EMP", 10),
                A.GOTO("nina-simon"),
            A.LABEL("end"),
                SET.MSG("( the bell rings, it's time for third period )"),
                A.WAIT(1.5f),
                SET.SCENE("third-period")
            ) },

        { "third-period", new Scene(
                SET.BG("class"),
                SET.TIME(1315),
                SET.MSG("( your counseling appointment )"),
                A.WAIT(),
                COND.IF(COND.GTE("GPA", 300),
                    SET.MSG("( you feel slightly nervous, but confident )"),
                    SET.MSG("( you are prepared for a lecture )")
                ),
                A.WAIT(),
                SET.MSG("( the counselor sits down across from you, reviewing papers )"),
                SET.CHOICES(
                    new Choice("Ask about a recommendation", A.GOTO("rec")),
                    new Choice("Wait")
                ),
                SET.MSG("'We're here to talk about your performance, which has been...'"),
                A.WAIT(),
                COND.IF(COND.LT("GPA", 300),
                    SET.MSG("'...degrading slightly, as of late.'"),
                    COND.IF(COND.GT("RBL", 30),
                        SET.MSG("'...somewhat erratic, lately.'"),
                        SET.MSG("'...very good, honestly.'"))
                    ),
                A.WAIT(2),
                SET.MSG("( this continues, uncomfortably, for the rest of the period )"),
                A.WAIT(2),
                SET.SCENE("PE"),
            A.LABEL("rec"),
                SET.MSG("( the counselor eyes you momentarily )"),
                A.WAIT(1.5f),
                COND.IF(COND.LT("GPA", 300), A.GOTO("rec-no")),
            A.LABEL("rec-yes"),
                SET.MSG("'I would be happy to write you a recommendation...'"),
                A.WAIT(),
                SET.MSG("( you feel a strong sense of relief for the rest of the period )"),
                SET.FLAG("recommendation"),
                A.WAIT(),
                SET.SCENE("PE"),
            A.LABEL("rec-no"),
                SET.MSG("'I'm afraid your recent performance hasn't warranted that...'"),
                A.WAIT(),
                SET.MSG("( you feel slight dread for the rest of the period )"),
                A.WAIT(),
                SET.SCENE("PE")) },

        { "charlotte", new Scene(
                SET.BG("charlotte"),
                SET.TIME(1315),
                SET.MSG("( Charlotte has taken you to... )"),
                SET.CHOICES(
                    new Choice("'An art studio?"),
                    new Choice("'Why are we here?'", A.GOTO("why"))
                ),
                SET.MSG("'Bingo! Aren't you clever.'"),
                A.WAIT(),
                INC.STAT("CLV", 1),
                A.GOTO("first"),        
            A.LABEL("why"),
                SET.MSG("'Because I wanted you to see it.'"),
                A.WAIT(2),
            A.LABEL("first"),
                SET.MSG("'You're the first person I've wanted to see it, actually.'"),
                A.WAIT(),
                SET.MSG("( you are surrounded by paintings in many styles )"),
                SET.CHOICES(
                    new Choice("'You're really good'"),
                    new Choice("'How long have you been painting?'", A.GOTO("how-long"))
                ),
                SET.MSG("'Well... thanks. I'm glad you like them.'"),
                A.WAIT(),
            A.LABEL("how-long"),
                SET.MSG("'I've been doing it in my spare time for a while.'"),
                A.WAIT(2),
                SET.MSG("'And now they're giving me class credit for studio time.'"),
                A.WAIT(),
                SET.MSG("( you continue to talk for a while longer )"),
                A.WAIT(),
                SET.FLAG("saw-studio"),
                SET.MSG("I should get back before next period."),
                A.WAIT(2),
                SET.SCENE("PE")
            ) },

        { "PE", new Scene(
                SET.TIME(1430),
                SET.BG("PE"),
                SET.MSG("PE class, a new distraction each day. Today, tennis."),
                A.WAIT(),
                SET.MSG("( ... )"),
                A.WAIT(2),
                SET.MSG("I'm up!"),
                A.WAIT(),
                SET.MSG("( hit the correct side in time with the ball )"),
                SET.CHOICES(null, new Choice("Serve")),
                A.WAIT(0.5f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    1f),
                A.WAIT(0.4f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    1f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    1f),
                A.WAIT(0.2f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                A.WAIT(0.2f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                A.WAIT(0.4f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                A.WAIT(1f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                A.WAIT(0.4f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                A.WAIT(0.5f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                A.WAIT(0.4f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                A.WAIT(1f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                A.WAIT(0.4f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                A.WAIT(0.5f),
                SET.CHOICES(
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    .8f),
                SET.CHOICES(
                    new Choice("BALL", A.MULTI(SET.MSG("'Good!'"), INC.STAT("POP", 2, false), A.SOUND("hit"))),
                    new Choice(" ", A.MULTI(SET.MSG("MISS", TextEffect.VIBRATE), INC.STAT("POP", -2, false))),
                    .8f),
                SET.MSG("Game!"),
                A.WAIT(4),
                SET.MSG("That was rather exhausting..."),
                A.WAIT(),
                SET.SCENE("open")) },

        { "open", new Scene (
                SET.TIME(1515),
                SET.BG("lockers"),
                SET.MSG("( before the end of the day, you have an open period )"),
                A.WAIT(),
                COND.IF(COND.FLAGGED("saw-studio"), 
                    A.GOTO("trouble"), 
                    A.GOTO("missing")),
            A.LABEL("normal"),
                COND.IF(COND.GTE("POP", 70), A.GOTO("ellie")),
                SET.MSG("( you make your way over to your locker )"),
                A.WAIT(),
                COND.IF(COND.FLAGGED("simon-mad"), A.NOOP(), A.GOTO("end")),
                SET.MSG("( ahead of you is Simon )"),
                SET.CHOICES(
                    new Choice("Avoid him", A.GOTO("avoid")),
                    new Choice("Talk with him"),
                    3
                ),
                SET.MSG("'Look, I'm really sorry about before.'"),
                COND.IF(COND.GTE("EMP", 30),
                    SET.CHOICES(
                        new Choice("'It's fine'"),
                        new Choice("'Listen, I understand'", A.GOTO("understand"))
                    ),
                    SET.CHOICES(
                        new Choice("'It's fine'"),
                        null
                    )
                ),
                SET.MSG("( Simon looks rather dejected )"),
                SET.CHOICES(
                    new Choice("'Just try not to snap at me next time?"),
                    new Choice("'If you need someone to talk to...'", A.GOTO("understand"))
                ),
                SET.MSG("'Of course.'"),
                A.WAIT(),
                SET.MSG("( you make smalltalk for a few minutes longer )"),
                A.WAIT(),
            A.LABEL("avoid"),
                SET.MSG("( you change direction before Simon sees you )"),
                A.WAIT(),
            A.LABEL("end"),
                SET.MSG("( nothing left to do for the day, you decide to head home )"),
                A.WAIT(4),
                SET.SCENE("end-bus"),
            A.LABEL("understand"),
                SET.MSG("'Thanks, really. I've been under a lot of pressure lately...'"),
                A.WAIT(),
                SET.MSG("( Simon opens up to you, right in front of your locker )"),
                A.WAIT(3),
                SET.MSG("( after talking for a while, you can see that Simon is relieved )"),
                A.WAIT(),
                INC.STAT("EMP", 20),
                SET.FLAG("helped-simon"),
                A.GOTO("end"),
            A.LABEL("ellie"),
                SET.MSG("( Ellie approaches and pulls you aside )"),
                A.WAIT(),
                SET.MSG("'Hi! Ready to hit the town?!'"),
                SET.CHOICES(
                    new Choice("'Well...'"),
                    new Choice("'Uh, I think?'"),
                    2.0f
                ),
                SET.MSG("'I won't take no for an answer, it's party time.'"),
                SET.CHOICES(
                    new Choice("'No, thanks.'"),
                    new Choice("Agree", A.GOTO("agree")),
                    2.0f
                ),
                SET.MSG("( Ellie's wide grin twists into a frown )"),
                A.WAIT(2),
                SET.MSG("'Fine then, suit yourself,' she spits."),
                A.WAIT(),
                INC.STAT("POP", -50),
                A.GOTO("normal"),
            A.LABEL("agree"),
                SET.MSG("( you and Ellie's group pile into her car )"),
                A.WAIT(),
                SET.MSG("( the car full and music blaring, you embark... )"),
                A.WAIT(5),
                SET.SCENE("credits"),
            A.LABEL("trouble"),
                SET.MSG("( your counselor approaches, visibly upset )"),
                A.WAIT(),
                SET.MSG("( nearby is the new kid, James )"),
                A.WAIT(),
                SET.MSG("'I'm really disappointed that you missed our appointment.'"),
                SET.CHOICES(
                    new Choice("'Oh, I was...'"),
                    new Choice("Stay quiet")
                ),
                COND.IF(COND.FLAGGED("nice-to-james"),
                    A.GOTO("james-help"),
                    COND.IF(COND.FLAGGED("mean-to-james"),
                        A.GOTO("james-blame")
                    )
                ),
                SET.MSG("'No explanation? See that you don't make that mistake again.'"),
                A.WAIT(),
                INC.STAT("GPA", -5),
                A.GOTO("normal"),
            A.LABEL("james-help"),
                SET.MSG("'Wait, there's a good reason for that.' James interjects."),
                A.WAIT(),
                SET.MSG("( he explains that you were helping him with schoolwork )"),
                A.WAIT(),
                SET.MSG("( your counselor considers this )"),
                A.WAIT(2),
                SET.MSG("'Well, that is what I like to see from students..."),
                A.WAIT(),
                SET.MSG("( after the counselor leaves, you thank James profulsely for his help )"),
                A.WAIT(),
                A.GOTO("normal"),
            A.LABEL("james-blame"),
                SET.MSG("'I saw what happened,' James interjects."),
                A.WAIT(),
                SET.MSG("( he claims he saw you leaving campus )"),
                A.WAIT(),
                SET.MSG("( your counselor is upset, giving you quite a lecture )"),
                A.WAIT(2),
                INC.STAT("GPA", -15),
                A.GOTO("normal"),
            A.LABEL("missing"),
                SET.MSG("( a police officer is talking to a faculty member nearby )"),
                A.WAIT(3),
                SET.MSG("( you overhear they mention the name Charlotte )"),
                SET.CHOICES(
                    new Choice("Stay out of it", A.GOTO("normal")),
                    new Choice("Investigate")
                ),
                SET.MSG("'What's going on?'"),
                A.WAIT(),
                SET.MSG("'We're looking for a student at this school, Charlotte Gibson, have you seen her today?'"),
                SET.CHOICES(
                    new Choice("'Yes, I have.'", A.GOTO("gone")),
                    new Choice("Lie")
                ),
                SET.MSG("'Tell one of your teachers, if you do.'"),
                A.WAIT(),
                A.GOTO("normal"),
            A.LABEL("gone"),
                SET.MSG("'She was supposed to pick up her young brother from daycare several hours ago...'"),
                A.WAIT(),
                SET.MSG("( Charlotte has gone missing )"),
                COND.IF(COND.FLAGGED("charlotte-lunch"),
                    SET.CHOICES(
                        new Choice("Stay out of it", A.GOTO("normal")),
                        new Choice("Go look for her")
                    ),
                    SET.CHOICES(
                        new Choice("Stay out of it", A.GOTO("normal")),
                        null
                    )
                ),
                SET.MSG("( you leave to look for Charlotte )"),
                A.WAIT(),
                SET.SCENE("find-charlotte")) },

        { "end-bus", new Scene(
                SET.BG("bus-inside"),
                SET.MSG("( you take the bus home )"),
                A.WAIT(),
                COND.IF(COND.FLAGGED("helped-simon"),
                    A.GOTO("thanks")),
                COND.IF(COND.FLAGGED("nice-to-james"),
                    A.GOTO("help")),
                COND.IF(COND.FLAGGED("recommendation"),
                    A.GOTO("rec")),
                SET.MSG("( on the way, you think about today, and the days that came before )"),
                A.WAIT(),
                SET.MSG("( you can't help but feel that some part of you is spinning away )"),
                A.WAIT(3),
                SET.MSG("( but you are still in control )"),
                A.WAIT(3),
                SET.MSG("( you're certain of it )"),
                A.WAIT(4),
                A.WAIT(),
                SET.SCENE("credits"),
            A.LABEL("rec"),
                SET.MSG("( on the way, you think about your counseling session )"),
                A.WAIT(),
                SET.MSG("( the recommendation might make all the difference for you )"),
                A.WAIT(3),
                SET.MSG("( or you may not need it after all )"),
                A.WAIT(3),
                SET.MSG("( more than ever, you feel a sense of confidence )"),
                A.WAIT(4),
                A.WAIT(),
                SET.SCENE("credits"),
            A.LABEL("help"),
                SET.MSG("( on the way, you get a message from James )"),
                A.WAIT(),
                SET.MSG("'Just wanted to say, thanks for reaching out today'"),
                A.WAIT(3),
                SET.MSG("'It makes all the difference.'"),
                A.WAIT(4),
                A.WAIT(),
                SET.SCENE("credits"),
            A.LABEL("thanks"),
                SET.MSG("( on the way, you get a message from Nina )"),
                A.WAIT(),
                SET.MSG("'Whatever you said to Simon... thank you.'"),
                A.WAIT(3),
                SET.MSG("'We're still on to study, right?! :D'"),
                A.WAIT(4),
                A.WAIT(),
                SET.SCENE("credits")
            ) },

        { "find-charlotte", new Scene(
                SET.TIME(1700),
                SET.BG("outside"),
                SET.MSG("( you get several people together to look for Charlotte )"),
                A.WAIT(5),
                SET.MSG("( you've looked all over town, there's no sign of her )"),
                COND.IF(COND.FLAGGED("laundromat"),
                    SET.CHOICES(
                        new Choice("Give up"),
                        new Choice("Keep looking", A.GOTO("idea"))
                    ),
                    SET.CHOICES(
                        new Choice("Give up", A.GOTO("give-up")),
                        new Choice("Keep looking")
                    )
                ),
            A.LABEL("no-luck"),
                SET.MSG("( you continue to search, but with no luck )"),
                SET.CHOICES(
                    new Choice("Give up", A.GOTO("give-up")),
                    new Choice("Keep looking", A.GOTO("idea"))
                ),
                INC.TIME(20),
                COND.IF(COND.AFTER(0800), A.GOTO("too-late")),
                SET.MSG("( not a trace )"),
                SET.CHOICES(
                    new Choice("Give up", A.GOTO("give-up")),
                    new Choice("Keep looking", A.GOTO("no-luck"))
                ),
            A.LABEL("too-late"),
                SET.MSG("( it's gotten too late to keep looking out here )"),
                A.WAIT(),
                A.GOTO("give-up"),
            A.LABEL("idea"),
                SET.MSG("( you remember something Charlotte said )"),
                SET.CHOICES(
                    null,
                    new Choice("Check the laundromat")
                ),
                SET.TIME(1730),
                SET.BG("laundromat"),
                SET.MSG("( you open the door to the laundromat, and... )"),
                A.WAIT(),
                SET.MSG("'Charlotte! There you are.'"),
                A.WAIT(),
                SET.MSG("( she looks up and smiles, through tears )"),
                A.WAIT(),
                SET.MSG("( even though you've only known her for the day )"),
                A.WAIT(3),
                SET.MSG("( even though when your day began she was a stranger )"),
                A.WAIT(3),
                SET.MSG("( you feel immense relief )"),
                A.WAIT(3),
                SET.MSG("( like something in you has changed )"),
                A.WAIT(5),
                A.WAIT(),
                SET.SCENE("credits"),
            A.LABEL("give-up"),
                SET.MSG("( you accept that you can't find Charlotte )"),
                A.WAIT(2),
                SET.MSG("( the police want a statement from you )"),
                A.WAIT(),
                SET.MSG("( maybe they can find her, but... )"),
                A.WAIT(2),
                SET.MSG("( it seems like she doesn't want to be found )"),
                A.WAIT(2),
                A.WAIT(),
                SET.SCENE("credits")) },

        { "credits", new Scene(
            SET.BG("credits"),
            SET.MSG("( press left or right to restart )"),
            A.WAIT(2),
            A.WAIT(),
            SET.SCENE("MENU")) }
    };

    public static Scene Get(string name) {
        return _lookup[name];
    }
}